'use client'

import { SecureStorage } from './secure-storage'
import { logger } from './logger'

export interface DataExport {
  version: string
  exportDate: string
  data: {
    // Données utilisateurs
    users: any[]
    userProfiles: any[]
    notifications: any[]
    watchHistory: any[]
    watchlist: any[]
    ratings: any[]
    currentUser: any
    adminUser: any
    userSessions: any
    bannedUsers: any[]
    userStats: any
    userPremium: any
    userAnalytics: any
    userPreferences: any
    userLocation: any
    
    // Données contenu
    movies: any[]
    series: any[]
    
    // Données analytics
    analytics: any
    
    // Données admin
    adminSettings: any
    adminSecurity: any
    adminErrors: any
    adminPremium: any
    adminHomepage: any
    homepageContent: any
    
    // Données premium et abonnement
    premiumCodes: any[]
    subscriptionPrice: any
    subscriptionNotifications: any
    subscriptionPlans: any
    postPaymentLinks: any
    postPaymentLinksActive: any
    paymentLinks: any
    paymentLinksActive: any
    postPaymentCodes: any
    postPaymentCodesActive: any
    
    // Données géographiques
    geographicRestrictions: any
    
    // Données système
    systemSettings: any
  }
}

export interface DataImportResult {
  success: boolean
  imported: {
    // Données utilisateurs
    users: number
    admins: number
    userProfiles: number
    notifications: number
    watchHistory: number
    watchlist: number
    ratings: number
    currentUser: boolean
    adminUser: boolean
    userSessions: boolean
    bannedUsers: number
    userStats: boolean
    userPremium: boolean
    userAnalytics: boolean
    userPreferences: boolean
    userLocation: boolean
    
    // Données contenu
    movies: number
    series: number
    
    // Données analytics
    analytics: boolean
    
    // Données admin
    adminSettings: boolean
    adminSecurity: boolean
    adminErrors: boolean
    adminPremium: boolean
    adminHomepage: boolean
    homepageContent: boolean
    
    // Données premium et abonnement
    premiumCodes: number
    subscriptionPrice: boolean
    subscriptionNotifications: boolean
    subscriptionPlans: boolean
    postPaymentLinks: boolean
    postPaymentLinksActive: boolean
    paymentLinks: boolean
    paymentLinksActive: boolean
    postPaymentCodes: boolean
    postPaymentCodesActive: boolean
    
    // Données géographiques
    geographicRestrictions: boolean
    
    // Données système
    systemSettings: boolean
  }
  errors: string[]
}

// Interfaces pour les sécurités
export interface SecurityCheck {
  isAuthenticated: boolean
  hasPermission: boolean
  isSessionValid: boolean
  adminInfo: {
    email: string
    name: string
    lastLogin: string
  }
}

export interface BackupInfo {
  id: string
  timestamp: string
  size: string
  description: string
  autoGenerated: boolean
}

export interface AuditLog {
  id: string
  action: string
  admin: string
  timestamp: string
  ip?: string
  userAgent?: string
  details: any
  success: boolean
}

export class DataManagementService {
  private static readonly EXPORT_VERSION = '1.0.0'
  
  // Sécurités pour VPS
  private static readonly CRITICAL_ACTIONS = ['DELETE_ALL_DATA', 'IMPORT_ALL_DATA']
  private static readonly BACKUP_PREFIX = 'atiha_backup_'

  // Export de toutes les données
  static async exportAllData(): Promise<DataExport> {
    try {
      const data = {
        // Données utilisateurs
        users: this.getStoredData('atiha_users_database'),
        userProfiles: this.getStoredData('atiha_user_profiles'),
        notifications: this.getStoredData('atiha_notifications'),
        watchHistory: this.getStoredData('atiha_watch_history'),
        watchlist: this.getStoredData('atiha_watchlist'),
        ratings: this.getStoredData('atiha_user_ratings'),
        currentUser: this.getStoredData('atiha_user'),
        adminUser: this.getStoredData('atiha_admin_user'),
        userSessions: this.getStoredData('atiha_user_sessions'),
        bannedUsers: this.getStoredData('atiha_banned_users'),
        userStats: this.getStoredData('atiha_user_stats'),
        userPremium: this.getStoredData('atiha_user_premium'),
        userAnalytics: this.getStoredData('atiha_user_analytics'),
        userPreferences: this.getStoredData('atiha_user_preferences'),
        userLocation: this.getStoredData('atiha_user_location'),
        
        // Données contenu
        movies: this.getStoredData('admin_movies'),
        series: this.getStoredData('admin_series'),
        
        // Données analytics
        analytics: this.getStoredData('atiha_analytics'),
        
        // Données admin
        adminSettings: this.getStoredData('atiha_admin_settings'),
        adminSecurity: this.getStoredData('atiha_admin_security'),
        adminErrors: this.getStoredData('atiha_admin_errors'),
        adminPremium: this.getStoredData('atiha_admin_premium'),
        adminHomepage: this.getStoredData('atiha_admin_homepage'),
        homepageContent: this.getStoredData('atiha_homepage_content'),
        
        // Données premium et abonnement
        premiumCodes: this.getStoredData('atiha_premium_codes'),
        subscriptionPrice: this.getStoredData('atiha_subscription_price'),
        subscriptionNotifications: this.getStoredData('atiha_subscription_notifications'),
        subscriptionPlans: this.getStoredData('atiha_subscription_plans'),
        postPaymentLinks: this.getStoredData('atiha_post_payment_links'),
        postPaymentLinksActive: this.getStoredData('atiha_post_payment_links_active'),
        paymentLinks: this.getStoredData('atiha_payment_links'),
        paymentLinksActive: this.getStoredData('atiha_payment_links_active'),
        postPaymentCodes: this.getStoredData('atiha_post_payment_codes'),
        postPaymentCodesActive: this.getStoredData('atiha_post_payment_codes_active'),
        
        // Données géographiques
        geographicRestrictions: this.getStoredData('atiha_geographic_restrictions'),
        
        // Données système
        systemSettings: this.getStoredData('atiha_system_settings')
      }

      return {
        version: this.EXPORT_VERSION,
        exportDate: new Date().toISOString(),
        data
      }
    } catch (error) {
      logger.error('Error exporting data', error as Error)
      throw new Error('Erreur lors de l\'export des données')
    }
  }

  // Import de toutes les données
  static async importAllData(file: File): Promise<DataImportResult> {
    try {
      const text = await file.text()
      const importData: DataExport = JSON.parse(text)

      // Vérifier la version
      if (importData.version !== this.EXPORT_VERSION) {
        throw new Error(`Version non supportée: ${importData.version}. Version attendue: ${this.EXPORT_VERSION}`)
      }

      const result: DataImportResult = {
        success: true,
        imported: {
          // Données utilisateurs
          users: 0,
          admins: 0,
          userProfiles: 0,
          notifications: 0,
          watchHistory: 0,
          watchlist: 0,
          ratings: 0,
          currentUser: false,
          adminUser: false,
          userSessions: false,
          bannedUsers: 0,
          userStats: false,
          userPremium: false,
          userAnalytics: false,
          userPreferences: false,
          userLocation: false,
          
          // Données contenu
          movies: 0,
          series: 0,
          
          // Données analytics
          analytics: false,
          
          // Données admin
          adminSettings: false,
          adminSecurity: false,
          adminErrors: false,
          adminPremium: false,
          adminHomepage: false,
          homepageContent: false,
          
          // Données premium et abonnement
          premiumCodes: 0,
          subscriptionPrice: false,
          subscriptionNotifications: false,
          subscriptionPlans: false,
          postPaymentLinks: false,
          postPaymentLinksActive: false,
          paymentLinks: false,
          paymentLinksActive: false,
          postPaymentCodes: false,
          postPaymentCodesActive: false,
          
          // Données géographiques
          geographicRestrictions: false,
          
          // Données système
          systemSettings: false
        },
        errors: []
      }

      // Importer chaque type de données
      try {
        if (importData.data.users) {
          this.setStoredData('atiha_users_database', importData.data.users)
          // Compter uniquement les utilisateurs normaux (sans les admins)
          const normalUsers = importData.data.users.filter((user: any) => !user.isAdmin)
          result.imported.users = normalUsers ? normalUsers.length : 0
          // Compter les admins parmi les utilisateurs importés
          result.imported.admins = importData.data.users.filter((user: any) => user.isAdmin === true).length
        }
      } catch (error) {
        result.errors.push(`Erreur import utilisateurs: ${error}`)
      }

      try {
        if (importData.data.movies) {
          this.setStoredData('admin_movies', importData.data.movies)
          result.imported.movies = importData.data.movies.length
        }
      } catch (error) {
        result.errors.push(`Erreur import films: ${error}`)
      }

      try {
        if (importData.data.series) {
          this.setStoredData('admin_series', importData.data.series)
          result.imported.series = importData.data.series.length
        }
      } catch (error) {
        result.errors.push(`Erreur import séries: ${error}`)
      }

      try {
        if (importData.data.analytics) {
          this.setStoredData('atiha_analytics', importData.data.analytics)
          result.imported.analytics = true
        }
      } catch (error) {
        result.errors.push(`Erreur import analytics: ${error}`)
      }

      try {
        if (importData.data.userProfiles) {
          this.setStoredData('atiha_user_profiles', importData.data.userProfiles)
          result.imported.userProfiles = importData.data.userProfiles.length
        }
      } catch (error) {
        result.errors.push(`Erreur import profils: ${error}`)
      }

      try {
        if (importData.data.notifications) {
          this.setStoredData('atiha_notifications', importData.data.notifications)
          result.imported.notifications = importData.data.notifications.length
        }
      } catch (error) {
        result.errors.push(`Erreur import notifications: ${error}`)
      }

      try {
        if (importData.data.watchHistory) {
          this.setStoredData('atiha_watch_history', importData.data.watchHistory)
          result.imported.watchHistory = importData.data.watchHistory.length
        }
      } catch (error) {
        result.errors.push(`Erreur import historique: ${error}`)
      }

      try {
        if (importData.data.watchlist) {
          this.setStoredData('atiha_watchlist', importData.data.watchlist)
          result.imported.watchlist = importData.data.watchlist.length
        }
      } catch (error) {
        result.errors.push(`Erreur import liste de souhaits: ${error}`)
      }

      try {
        if (importData.data.ratings) {
          this.setStoredData('atiha_user_ratings', importData.data.ratings)
          result.imported.ratings = importData.data.ratings.length
        }
      } catch (error) {
        result.errors.push(`Erreur import notes: ${error}`)
      }

      // Importer les données utilisateur supplémentaires
      try {
        if (importData.data.currentUser) {
          this.setStoredData('atiha_user', importData.data.currentUser)
          result.imported.currentUser = true
        }
      } catch (error) {
        result.errors.push(`Erreur import utilisateur actuel: ${error}`)
      }

      try {
        if (importData.data.adminUser) {
          this.setStoredData('atiha_admin_user', importData.data.adminUser)
          result.imported.adminUser = true
        }
      } catch (error) {
        result.errors.push(`Erreur import utilisateur admin: ${error}`)
      }

      try {
        if (importData.data.userSessions) {
          this.setStoredData('atiha_user_sessions', importData.data.userSessions)
          result.imported.userSessions = true
        }
      } catch (error) {
        result.errors.push(`Erreur import sessions utilisateur: ${error}`)
      }

      try {
        if (importData.data.bannedUsers) {
          this.setStoredData('atiha_banned_users', importData.data.bannedUsers)
          result.imported.bannedUsers = importData.data.bannedUsers.length
        }
      } catch (error) {
        result.errors.push(`Erreur import utilisateurs bannis: ${error}`)
      }

      try {
        if (importData.data.userStats) {
          this.setStoredData('atiha_user_stats', importData.data.userStats)
          result.imported.userStats = true
        }
      } catch (error) {
        result.errors.push(`Erreur import statistiques utilisateur: ${error}`)
      }

      try {
        if (importData.data.userPremium) {
          this.setStoredData('atiha_user_premium', importData.data.userPremium)
          result.imported.userPremium = true
        }
      } catch (error) {
        result.errors.push(`Erreur import premium utilisateur: ${error}`)
      }

      try {
        if (importData.data.userAnalytics) {
          this.setStoredData('atiha_user_analytics', importData.data.userAnalytics)
          result.imported.userAnalytics = true
        }
      } catch (error) {
        result.errors.push(`Erreur import analytics utilisateur: ${error}`)
      }

      try {
        if (importData.data.userPreferences) {
          this.setStoredData('atiha_user_preferences', importData.data.userPreferences)
          result.imported.userPreferences = true
        }
      } catch (error) {
        result.errors.push(`Erreur import préférences utilisateur: ${error}`)
      }

      try {
        if (importData.data.userLocation) {
          this.setStoredData('atiha_user_location', importData.data.userLocation)
          result.imported.userLocation = true
        }
      } catch (error) {
        result.errors.push(`Erreur import localisation utilisateur: ${error}`)
      }

      // Importer les données admin
      try {
        if (importData.data.adminSettings) {
          this.setStoredData('atiha_admin_settings', importData.data.adminSettings)
          result.imported.adminSettings = true
        }
      } catch (error) {
        result.errors.push(`Erreur import paramètres admin: ${error}`)
      }

      try {
        if (importData.data.adminSecurity) {
          this.setStoredData('atiha_admin_security', importData.data.adminSecurity)
          result.imported.adminSecurity = true
        }
      } catch (error) {
        result.errors.push(`Erreur import sécurité admin: ${error}`)
      }

      try {
        if (importData.data.adminErrors) {
          this.setStoredData('atiha_admin_errors', importData.data.adminErrors)
          result.imported.adminErrors = true
        }
      } catch (error) {
        result.errors.push(`Erreur import erreurs admin: ${error}`)
      }

      try {
        if (importData.data.adminPremium) {
          this.setStoredData('atiha_admin_premium', importData.data.adminPremium)
          result.imported.adminPremium = true
        }
      } catch (error) {
        result.errors.push(`Erreur import premium admin: ${error}`)
      }

      try {
        if (importData.data.adminHomepage) {
          this.setStoredData('atiha_admin_homepage', importData.data.adminHomepage)
          result.imported.adminHomepage = true
        }
      } catch (error) {
        result.errors.push(`Erreur import homepage admin: ${error}`)
      }

      try {
        if (importData.data.homepageContent) {
          this.setStoredData('atiha_homepage_content', importData.data.homepageContent)
          result.imported.homepageContent = true
        }
      } catch (error) {
        result.errors.push(`Erreur import contenu homepage: ${error}`)
      }

      // Importer les données premium et abonnement
      try {
        if (importData.data.premiumCodes) {
          this.setStoredData('atiha_premium_codes', importData.data.premiumCodes)
          result.imported.premiumCodes = importData.data.premiumCodes.length
        }
      } catch (error) {
        result.errors.push(`Erreur import codes premium: ${error}`)
      }

      try {
        if (importData.data.subscriptionPrice) {
          this.setStoredData('atiha_subscription_price', importData.data.subscriptionPrice)
          result.imported.subscriptionPrice = true
        }
      } catch (error) {
        result.errors.push(`Erreur import prix abonnement: ${error}`)
      }

      try {
        if (importData.data.subscriptionNotifications) {
          this.setStoredData('atiha_subscription_notifications', importData.data.subscriptionNotifications)
          result.imported.subscriptionNotifications = true
        }
      } catch (error) {
        result.errors.push(`Erreur import notifications abonnement: ${error}`)
      }

      try {
        if (importData.data.subscriptionPlans) {
          this.setStoredData('atiha_subscription_plans', importData.data.subscriptionPlans)
          result.imported.subscriptionPlans = true
        }
      } catch (error) {
        result.errors.push(`Erreur import plans abonnement: ${error}`)
      }

      try {
        if (importData.data.postPaymentLinks) {
          this.setStoredData('atiha_post_payment_links', importData.data.postPaymentLinks)
          result.imported.postPaymentLinks = true
        }
      } catch (error) {
        result.errors.push(`Erreur import liens après paiement: ${error}`)
      }

      try {
        if (importData.data.postPaymentLinksActive) {
          this.setStoredData('atiha_post_payment_links_active', importData.data.postPaymentLinksActive)
          result.imported.postPaymentLinksActive = true
        }
      } catch (error) {
        result.errors.push(`Erreur import état liens après paiement: ${error}`)
      }

      try {
        if (importData.data.paymentLinks) {
          this.setStoredData('atiha_payment_links', importData.data.paymentLinks)
          result.imported.paymentLinks = true
        }
      } catch (error) {
        result.errors.push(`Erreur import liens de paiement: ${error}`)
      }

      try {
        if (importData.data.paymentLinksActive) {
          this.setStoredData('atiha_payment_links_active', importData.data.paymentLinksActive)
          result.imported.paymentLinksActive = true
        }
      } catch (error) {
        result.errors.push(`Erreur import état liens de paiement: ${error}`)
      }

      try {
        if (importData.data.postPaymentCodes) {
          this.setStoredData('atiha_post_payment_codes', importData.data.postPaymentCodes)
          result.imported.postPaymentCodes = true
        }
      } catch (error) {
        result.errors.push(`Erreur import codes après paiement: ${error}`)
      }

      try {
        if (importData.data.postPaymentCodesActive) {
          this.setStoredData('atiha_post_payment_codes_active', importData.data.postPaymentCodesActive)
          result.imported.postPaymentCodesActive = true
        }
      } catch (error) {
        result.errors.push(`Erreur import état codes après paiement: ${error}`)
      }

      // Importer les données géographiques
      try {
        if (importData.data.geographicRestrictions) {
          this.setStoredData('atiha_geographic_restrictions', importData.data.geographicRestrictions)
          result.imported.geographicRestrictions = true
        }
      } catch (error) {
        result.errors.push(`Erreur import restrictions géographiques: ${error}`)
      }

      // Importer les données système
      try {
        if (importData.data.systemSettings) {
          this.setStoredData('atiha_system_settings', importData.data.systemSettings)
          result.imported.systemSettings = true
        }
      } catch (error) {
        result.errors.push(`Erreur import paramètres système: ${error}`)
      }

      // Marquer comme échec si trop d&apos;erreurs
      if (result.errors.length > 3) {
        result.success = false
      }

      return result
    } catch (error) {
      logger.error('Error importing data', error as Error)
      return {
        success: false,
        imported: {
          users: 0,
          admins: 0,
          movies: 0,
          series: 0,
          analytics: false,
          userProfiles: 0,
          notifications: 0,
          watchHistory: 0,
          watchlist: 0,
          ratings: 0,
          currentUser: false,
          adminUser: false,
          userSessions: false,
          bannedUsers: 0,
          userStats: false,
          userPremium: false,
          userAnalytics: false,
          userPreferences: false,
          userLocation: false,
          adminSettings: false,
          adminSecurity: false,
          adminErrors: false,
          adminPremium: false,
          adminHomepage: false,
          homepageContent: false,
          premiumCodes: 0,
          subscriptionPrice: false,
          subscriptionNotifications: false,
          subscriptionPlans: false,
          postPaymentLinks: false,
          postPaymentLinksActive: false,
          paymentLinks: false,
          paymentLinksActive: false,
          postPaymentCodes: false,
          postPaymentCodesActive: false,
          geographicRestrictions: false,
          systemSettings: false
        },
        errors: [`Erreur lors de l&apos;import: ${error}`]
      }
    }
  }

  // Suppression de toutes les données (en préservant l'admin leGenny)
  static async deleteAllData(): Promise<void> {
    try {
      if (process.env.NODE_ENV === 'development') {
        logger.debug('Suppression de toutes les données (préservation de l\'admin leGenny)')
      }
      
      // Sauvegarder l'admin leGenny depuis la base de données utilisateurs
      const usersDatabase = this.getStoredData('atiha_users_database')
      let leGennyAdmin = null
      
      if (usersDatabase && Array.isArray(usersDatabase)) {
        leGennyAdmin = usersDatabase.find(user => 
          user.email === 'leGenny' || user.name === 'leGenny' || user.username === 'leGenny'
        )
      }
      
      if (process.env.NODE_ENV === 'development') {
        logger.debug('Admin leGenny trouvé', { found: leGennyAdmin ? 'Oui' : 'Non' })
      }
      if (leGennyAdmin) {
        if (process.env.NODE_ENV === 'development') {
          logger.debug('Détails leGenny', { email: leGennyAdmin.email, name: leGennyAdmin.name })
        }
      }

      const keysToDelete = [
        // Données utilisateurs
        'atiha_users_database',
        'atiha_user_profiles',
        'atiha_notifications',
        'atiha_watch_history',
        'atiha_watchlist',
        'atiha_user_ratings',
        'atiha_user_sessions',
        'atiha_banned_users',
        'atiha_user',
        'atiha_admin_user',
        'atiha_user_stats',
        'atiha_user_premium',
        'atiha_user_analytics',
        'atiha_user_preferences',
        'atiha_user_location',
        
        // Données contenu
        'admin_movies',
        'admin_series',
        
        // Données analytics
        'atiha_analytics',
        
        // Données admin
        'atiha_admin_settings',
        'atiha_admin_security',
        'atiha_admin_errors',
        'atiha_admin_premium',
        'atiha_admin_homepage',
        'atiha_homepage_content',
        'atiha_admin_lockout',
        'atiha_admin_attempts',
        
        // Données premium et abonnement
        'atiha_premium_codes',
        'atiha_subscription_price',
        'atiha_subscription_notifications',
        'atiha_subscription_plans',
        'atiha_post_payment_links',
        'atiha_post_payment_links_active',
        'atiha_payment_links',
        'atiha_payment_links_active',
        'atiha_post_payment_codes',
        'atiha_post_payment_codes_active',
        
        // Données géographiques
        'atiha_geographic_restrictions',
        
        // Données système
        'atiha_system_settings'
      ]

      // Supprimer toutes les clés
      keysToDelete.forEach(key => {
        localStorage.removeItem(key)
      })

      // Restaurer l'admin leGenny dans la base de données utilisateurs
      if (leGennyAdmin) {
        const restoredUsers = [leGennyAdmin]
        this.setStoredData('atiha_users_database', restoredUsers)
        if (process.env.NODE_ENV === 'development') {
          logger.info('Admin leGenny restauré dans la base de données utilisateurs')
        }
      }

      if (process.env.NODE_ENV === 'development') {
        logger.info('Toutes les données ont été supprimées (admin leGenny préservé)')
      }
    } catch (error) {
      logger.error('Erreur lors de la suppression des données', error as Error)
      throw new Error('Erreur lors de la suppression des données')
    }
  }

  // Suppression automatique lors du verrouillage
  static async deleteDataOnLockout(): Promise<void> {
    try {
      if (process.env.NODE_ENV === 'development') {
        logger.warn('Admin account locked - Deleting all data for security')
      }
      
      // Supprimer toutes les données utilisateur
      await this.deleteAllData()
      
      // Recréer les utilisateurs par défaut
      await this.recreateDefaultUsers()
      
      if (process.env.NODE_ENV === 'development') {
        logger.info('Data deletion and default users recreation completed')
      }
    } catch (error) {
      logger.error('Error during lockout data deletion', error as Error)
    }
  }

  // Recréer les utilisateurs par défaut (en préservant l'admin leGenny)
  private static async recreateDefaultUsers(): Promise<void> {
    try {
      // Vérifier si l'admin leGenny existe déjà dans la base de données
      const existingUsers = this.getStoredData('atiha_users_database') || []
      const existingLeGenny = existingUsers.find((user: any) => 
        user.email === 'leGenny' || user.name === 'leGenny' || user.username === 'leGenny'
      )
      
      const defaultUsers = [
        {
          id: 'admin_demo',
          email: 'admin@user.com',
          name: 'Admin user',
          phone: '+000000000001',
          password: process.env.ADMIN_DEFAULT_PASSWORD || `admin_temp_${Date.now()}`,
          country: 'MA',
          isActive: true,
          isBanned: false,
          loginCount: 0,
          registrationDate: new Date().toISOString(),
          createdAt: new Date()
        }
      ]

      // Ajouter l'admin leGenny s'il existe
      if (existingLeGenny) {
        defaultUsers.unshift(existingLeGenny)
        if (process.env.NODE_ENV === 'development') {
          logger.info('Admin leGenny inclus dans la recréation des utilisateurs par défaut')
        }
      }

      localStorage.setItem('atiha_users_database', JSON.stringify(defaultUsers))
      
      if (process.env.NODE_ENV === 'development') {
        logger.info('Default users recreated (admin leGenny préservé)')
      }
    } catch (error) {
      logger.error('Error recreating default users', error as Error)
    }
  }

  // Méthodes utilitaires
  private static getStoredData(key: string): any {
    if (typeof window === 'undefined') return null
    
    try {
      // Utiliser SecureStorage pour déchiffrer automatiquement si la clé est sensible
      return SecureStorage.getItemJSON(key)
    } catch (error) {
      logger.error(`Error getting stored data for key ${key}`, error as Error)
      return null
    }
  }

  private static setStoredData(key: string, data: any): void {
    if (typeof window === 'undefined') return
    
    try {
      // Utiliser SecureStorage pour chiffrer automatiquement si la clé est sensible
      SecureStorage.setItem(key, data)
    } catch (error) {
      logger.error(`Error setting stored data for key ${key}`, error as Error)
      throw error
    }
  }

  // Vérifier l&apos;intégrité des données
  static async verifyDataIntegrity(): Promise<{
    isValid: boolean
    issues: string[]
  }> {
    const issues: string[] = []

    try {
      // Vérifier les utilisateurs
      const users = this.getStoredData('atiha_users_database')
      if (!users || !Array.isArray(users)) {
        issues.push('Données utilisateurs corrompues ou manquantes')
      }

      // Vérifier les films
      const movies = this.getStoredData('admin_movies')
      if (!movies || !Array.isArray(movies)) {
        issues.push('Données films corrompues ou manquantes')
      }

      // Vérifier les séries
      const series = this.getStoredData('admin_series')
      if (!series || !Array.isArray(series)) {
        issues.push('Données séries corrompues ou manquantes')
      }

      return {
        isValid: issues.length === 0,
        issues
      }
    } catch (error) {
      return {
        isValid: false,
        issues: [`Erreur lors de la vérification: ${error}`]
      }
    }
  }

  // Obtenir les statistiques des données
  static getDataStats(): {
    // Données utilisateurs
    users: number
    admins: number
    notifications: number
    watchHistory: number
    watchlist: number
    ratings: number
    currentUser: boolean
    adminUser: boolean
    userSessions: boolean
    bannedUsers: number
    userStats: boolean
    userPremium: boolean
    userAnalytics: boolean
    userPreferences: boolean
    userLocation: boolean
    
    // Données contenu
    movies: number
    series: number
    
    // Données analytics
    analytics: boolean
    
    // Données admin
    adminSettings: boolean
    adminSecurity: boolean
    adminErrors: boolean
    adminPremium: boolean
    adminHomepage: boolean
    homepageContent: boolean
    
    // Données premium et abonnement
    premiumCodes: number
    subscriptionPrice: boolean
    subscriptionNotifications: boolean
    subscriptionPlans: boolean
    postPaymentLinks: boolean
    postPaymentLinksActive: boolean
    paymentLinks: boolean
    paymentLinksActive: boolean
    postPaymentCodes: boolean
    postPaymentCodesActive: boolean
    
    // Données géographiques
    geographicRestrictions: boolean
    
    // Données système
    systemSettings: boolean
    
    // Statistiques générales
    totalSize: string
  } {
    const stats = {
      // Données utilisateurs
      users: 0,
      admins: 0,
      notifications: 0,
      watchHistory: 0,
      watchlist: 0,
      ratings: 0,
      currentUser: false,
      adminUser: false,
      userSessions: false,
      bannedUsers: 0,
      userStats: false,
      userPremium: false,
      userAnalytics: false,
      userPreferences: false,
      userLocation: false,
      
      // Données contenu
      movies: 0,
      series: 0,
      
      // Données analytics
      analytics: false,
      
      // Données admin
      adminSettings: false,
      adminSecurity: false,
      adminErrors: false,
      adminPremium: false,
      adminHomepage: false,
      homepageContent: false,
      
      // Données premium et abonnement
      premiumCodes: 0,
      subscriptionPrice: false,
      subscriptionNotifications: false,
      subscriptionPlans: false,
      postPaymentLinks: false,
      postPaymentLinksActive: false,
      paymentLinks: false,
      paymentLinksActive: false,
      postPaymentCodes: false,
      postPaymentCodesActive: false,
      
      // Données géographiques
      geographicRestrictions: false,
      
      // Données système
      systemSettings: false,
      
      // Statistiques générales
      totalSize: '0 KB'
    }

    try {
      // Compter uniquement les utilisateurs normaux (sans les admins)
      const users = this.getStoredData('atiha_users_database')
      if (users && Array.isArray(users)) {
        const normalUsers = users.filter((user: any) => !user.isAdmin)
        stats.users = normalUsers ? normalUsers.length : 0
      } else {
        stats.users = 0
      }

      const movies = this.getStoredData('admin_movies')
      stats.movies = movies ? movies.length : 0

      const series = this.getStoredData('admin_series')
      stats.series = series ? series.length : 0

      const analytics = this.getStoredData('atiha_analytics')
      stats.analytics = analytics !== null

      // Compter les administrateurs
      try {
        const userDatabaseData = this.getStoredData('atiha_users_database')
        if (userDatabaseData && Array.isArray(userDatabaseData)) {
          const admins = userDatabaseData.filter((user: any) => user.isAdmin === true)
          stats.admins = admins ? admins.length : 0
        } else {
          stats.admins = 0
        }
      } catch (error) {
        logger.error('Error loading admins', error as Error)
        stats.admins = 0
      }

      const notifications = this.getStoredData('atiha_notifications')
      stats.notifications = notifications ? notifications.length : 0

      const watchHistory = this.getStoredData('atiha_watch_history')
      stats.watchHistory = watchHistory ? watchHistory.length : 0

      const watchlist = this.getStoredData('atiha_watchlist')
      stats.watchlist = watchlist ? watchlist.length : 0

      const ratings = this.getStoredData('atiha_user_ratings')
      stats.ratings = ratings ? ratings.length : 0

      // Vérifier les données utilisateur supplémentaires
      const currentUser = this.getStoredData('atiha_user')
      stats.currentUser = currentUser !== null

      const adminUser = this.getStoredData('atiha_admin_user')
      stats.adminUser = adminUser !== null

      const userSessions = this.getStoredData('atiha_user_sessions')
      stats.userSessions = userSessions !== null

      const bannedUsers = this.getStoredData('atiha_banned_users')
      stats.bannedUsers = bannedUsers ? bannedUsers.length : 0

      const userStats = this.getStoredData('atiha_user_stats')
      stats.userStats = userStats !== null

      const userPremium = this.getStoredData('atiha_user_premium')
      stats.userPremium = userPremium !== null

      const userAnalytics = this.getStoredData('atiha_user_analytics')
      stats.userAnalytics = userAnalytics !== null

      const userPreferences = this.getStoredData('atiha_user_preferences')
      stats.userPreferences = userPreferences !== null

      const userLocation = this.getStoredData('atiha_user_location')
      stats.userLocation = userLocation !== null

      // Vérifier les données admin
      const adminSettings = this.getStoredData('atiha_admin_settings')
      stats.adminSettings = adminSettings !== null

      const adminSecurity = this.getStoredData('atiha_admin_security')
      stats.adminSecurity = adminSecurity !== null

      const adminErrors = this.getStoredData('atiha_admin_errors')
      stats.adminErrors = adminErrors !== null

      const adminPremium = this.getStoredData('atiha_admin_premium')
      stats.adminPremium = adminPremium !== null

      const adminHomepage = this.getStoredData('atiha_admin_homepage')
      stats.adminHomepage = adminHomepage !== null

      const homepageContent = this.getStoredData('atiha_homepage_content')
      stats.homepageContent = homepageContent !== null

      // Vérifier les données premium et abonnement
      const premiumCodes = this.getStoredData('atiha_premium_codes')
      stats.premiumCodes = premiumCodes ? premiumCodes.length : 0

      const subscriptionPrice = this.getStoredData('atiha_subscription_price')
      stats.subscriptionPrice = subscriptionPrice !== null

      const subscriptionNotifications = this.getStoredData('atiha_subscription_notifications')
      stats.subscriptionNotifications = subscriptionNotifications !== null

      const subscriptionPlans = this.getStoredData('atiha_subscription_plans')
      stats.subscriptionPlans = subscriptionPlans !== null

      const postPaymentLinks = this.getStoredData('atiha_post_payment_links')
      stats.postPaymentLinks = postPaymentLinks !== null

      const postPaymentLinksActive = this.getStoredData('atiha_post_payment_links_active')
      stats.postPaymentLinksActive = postPaymentLinksActive !== null

      const paymentLinks = this.getStoredData('atiha_payment_links')
      stats.paymentLinks = paymentLinks !== null

      const paymentLinksActive = this.getStoredData('atiha_payment_links_active')
      stats.paymentLinksActive = paymentLinksActive !== null

      const postPaymentCodes = this.getStoredData('atiha_post_payment_codes')
      stats.postPaymentCodes = postPaymentCodes !== null

      const postPaymentCodesActive = this.getStoredData('atiha_post_payment_codes_active')
      stats.postPaymentCodesActive = postPaymentCodesActive !== null

      // Vérifier les données géographiques
      const geographicRestrictions = this.getStoredData('atiha_geographic_restrictions')
      stats.geographicRestrictions = geographicRestrictions !== null

      // Vérifier les données système
      const systemSettings = this.getStoredData('atiha_system_settings')
      stats.systemSettings = systemSettings !== null

      // Calculer la taille totale
      let totalSize = 0
      for (let i = 0; i < localStorage.length; i++) {
        const key = localStorage.key(i)
        if (key && key.startsWith('atiha_')) {
          const value = localStorage.getItem(key)
          if (value) {
            totalSize += value.length
          }
        }
      }

      stats.totalSize = this.formatBytes(totalSize)

      return stats
    } catch (error) {
      logger.error('Error getting data stats', error as Error)
      return stats
    }
  }

  private static formatBytes(bytes: number): string {
    if (bytes === 0) return '0 Bytes'
    const k = 1024
    const sizes = ['Bytes', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
  }

  // ===== SÉCURITÉS POUR VPS =====

  // Détecter l'admin actuellement connecté
  private static getCurrentLoggedInAdmin(): any {
    try {
      // Méthode 1: Vérifier le localStorage pour l'utilisateur connecté
      const currentUser = this.getStoredData('atiha_user')
      if (currentUser && currentUser.isAdmin) {
        if (process.env.NODE_ENV === 'development') {
          logger.debug('Admin connecté trouvé dans localStorage')
        }
        return currentUser
      }

      // Méthode 2: Vérifier les sessions actives
      const activeSessions = this.getStoredData('atiha_user_sessions')
      if (activeSessions && Array.isArray(activeSessions)) {
        const activeSession = activeSessions.find(session => 
          session.isActive && session.user && session.user.isAdmin
        )
        if (activeSession) {
          if (process.env.NODE_ENV === 'development') {
            logger.debug('Admin connecté trouvé dans les sessions')
          }
          return activeSession.user
        }
      }

      // Méthode 3: Vérifier le dernier utilisateur connecté
      const lastLogin = this.getStoredData('atiha_last_login')
      if (lastLogin && lastLogin.user && lastLogin.user.isAdmin) {
        if (process.env.NODE_ENV === 'development') {
          logger.debug('Admin connecté trouvé dans lastLogin')
        }
        return lastLogin.user
      }

      // Méthode 4: Chercher dans la base de données des utilisateurs
      const users = this.getStoredData('atiha_users_database')
      if (users && Array.isArray(users)) {
        // Chercher un admin récemment connecté (dernière heure)
        const recentTime = new Date(Date.now() - 60 * 60 * 1000) // 1 heure
        const recentAdmin = users.find(user => 
          user.isAdmin && 
          user.lastLogin && 
          new Date(user.lastLogin) > recentTime
        )
        if (recentAdmin) {
          if (process.env.NODE_ENV === 'development') {
            logger.debug('Admin récemment connecté trouvé')
          }
          return recentAdmin
        }
      }

      if (process.env.NODE_ENV === 'development') {
        logger.debug('Aucun admin connecté détecté')
      }
      return null
    } catch (error) {
      logger.error('Erreur lors de la détection de l\'admin connecté', error as Error)
      return null
    }
  }

  // Vérification de sécurité pour actions critiques
  static async performSecurityCheck(action: string): Promise<SecurityCheck> {
    try {
      // Détecter l'admin actuellement connecté
      let currentUser = this.getCurrentLoggedInAdmin()
      
      // Si pas d'admin connecté, essayer de trouver un admin dans la base de données
      if (!currentUser) {
        logger.debug('Recherche d\'un admin dans la base de données')
        
        // Chercher dans la base de données des utilisateurs
        const users = this.getStoredData('atiha_users_database')
        if (users && Array.isArray(users)) {
          const adminUser = users.find(user => user.isAdmin === true)
          if (adminUser) {
            if (process.env.NODE_ENV === 'development') {
              logger.info('Admin trouvé dans la base de données')
            }
            currentUser = {
              ...adminUser,
              lastLogin: new Date().toISOString()
            }
          }
        }
        
        // Si toujours pas d'admin, créer un admin par défaut pour le développement
        if (!currentUser) {
          if (process.env.NODE_ENV === 'development') {
            logger.debug('Création d\'un admin par défaut pour le développement')
          }
          currentUser = {
            id: 'admin_dev',
            email: 'admin@dev.com',
            name: 'Admin Développement',
            isAdmin: true,
            isSuperAdmin: true,
            permissions: ['DATA_MANAGEMENT', 'ADMIN_ACCESS', 'USER_MANAGEMENT'],
            lastLogin: new Date().toISOString()
          }
        }
      }

      // Vérifier si c'est un admin
      if (!currentUser.isAdmin) {
        throw new Error('Accès refusé - Admin requis')
      }

      // Vérifier la session (plus permissif en développement)
      const sessionValid = this.isSessionValid(currentUser)
      if (!sessionValid && !currentUser.isSuperAdmin) {
        throw new Error('Session expirée - Reconnexion requise')
      }

      // Vérifier les permissions
      const hasPermission = this.hasDataManagementPermission(currentUser)
      if (!hasPermission) {
        throw new Error('Permissions insuffisantes')
      }

      return {
        isAuthenticated: true,
        hasPermission: true,
        isSessionValid: true,
        adminInfo: {
          email: currentUser.email,
          name: currentUser.name,
          lastLogin: currentUser.lastLogin || new Date().toISOString()
        }
      }
    } catch (error) {
      logger.error('Security check failed', error as Error)
      throw new Error(`Vérification de sécurité échouée: ${error}`)
    }
  }

  // Créer un backup automatique
  static async createAutomaticBackup(description: string = 'Backup automatique'): Promise<BackupInfo> {
    try {
      const backupId = `${this.BACKUP_PREFIX}${Date.now()}`
      const timestamp = new Date().toISOString()
      
      // Exporter toutes les données
      const exportData = await this.exportAllData()
      
      // Calculer la taille
      const dataString = JSON.stringify(exportData)
      const size = this.formatBytes(dataString.length)
      
      // Sauvegarder le backup
      const backupInfo: BackupInfo = {
        id: backupId,
        timestamp,
        size,
        description,
        autoGenerated: true
      }
      
      // Stocker le backup
      localStorage.setItem(backupId, dataString)
      localStorage.setItem(`${backupId}_info`, JSON.stringify(backupInfo))
      
      // Log de l'action
      await this.logAuditAction('CREATE_BACKUP', {
        backupId,
        description,
        size
      })
      
      return backupInfo
    } catch (error) {
      logger.error('Error creating backup', error as Error)
      throw new Error(`Erreur lors de la création du backup: ${error}`)
    }
  }

  // Log d'audit pour les actions critiques
  static async logAuditAction(action: string, details: any): Promise<void> {
    try {
      const currentUser = this.getStoredData('atiha_user')
      const logId = `audit_${Date.now()}_${Math.random().toString(36).substr(2, 9)}`
      
      const auditLog: AuditLog = {
        id: logId,
        action,
        admin: currentUser?.email || 'unknown',
        timestamp: new Date().toISOString(),
        ip: 'localhost', // À remplacer par l'IP réelle sur VPS
        userAgent: navigator.userAgent,
        details,
        success: true
      }
      
      // Récupérer les logs existants
      const existingLogs = this.getStoredData('atiha_audit_logs') || []
      existingLogs.push(auditLog)
      
      // Garder seulement les 100 derniers logs
      if (existingLogs.length > 100) {
        existingLogs.splice(0, existingLogs.length - 100)
      }
      
      // Sauvegarder
      localStorage.setItem('atiha_audit_logs', JSON.stringify(existingLogs))
    } catch (error) {
      logger.error('Error logging audit action', error as Error)
    }
  }

  // Vérifier si la session est valide
  private static isSessionValid(user: any): boolean {
    if (!user || !user.lastLogin) return false
    
    const lastLogin = new Date(user.lastLogin)
    const now = new Date()
    const sessionTimeout = 24 * 60 * 60 * 1000 // 24 heures
    
    return (now.getTime() - lastLogin.getTime()) < sessionTimeout
  }

  // Vérifier les permissions de gestion des données
  private static hasDataManagementPermission(user: any): boolean {
    if (!user || !user.isAdmin) return false
    
    // Si c'est un super admin, autoriser automatiquement
    if (user.isSuperAdmin) return true
    
    // Si c'est un admin normal, vérifier les permissions
    if (user.permissions && Array.isArray(user.permissions)) {
      return user.permissions.includes('DATA_MANAGEMENT')
    }
    
    // Si pas de permissions définies mais que c'est un admin, autoriser par défaut
    if (user.isAdmin) return true
    
    return false
  }

  // Générer un rapport de suppression
  static async generateDeletionReport(): Promise<{
    users: number
    movies: number
    series: number
    totalSize: string
    impact: string
  }> {
    try {
      const stats = this.getDataStats()
      
      return {
        users: stats.users,
        movies: stats.movies,
        series: stats.series,
        totalSize: stats.totalSize,
        impact: stats.users > 100 ? 'IMPACT ÉLEVÉ' : 'IMPACT MODÉRÉ'
      }
    } catch (error) {
      logger.error('Error generating deletion report', error as Error)
      throw new Error(`Erreur lors de la génération du rapport: ${error}`)
    }
  }

  // Méthodes sécurisées pour les actions critiques
  static async secureDeleteAllData(): Promise<void> {
    try {
      // 1. Vérification de sécurité
      await this.performSecurityCheck('DELETE_ALL_DATA')
      
      // 2. Créer backup automatique
      const backup = await this.createAutomaticBackup('Backup avant suppression complète')
      
      // 3. Log de l'action
      await this.logAuditAction('DELETE_ALL_DATA_INITIATED', {
        backupId: backup.id,
        timestamp: backup.timestamp
      })
      
      // 4. Effectuer la suppression
      await this.deleteAllData()
      
      // 5. Log de succès
      await this.logAuditAction('DELETE_ALL_DATA_COMPLETED', {
        backupId: backup.id,
        success: true
      })
      
    } catch (error) {
      // Log de l'erreur
      await this.logAuditAction('DELETE_ALL_DATA_FAILED', {
        error: (error as Error).toString(),
        success: false
      })
      throw error
    }
  }

  static async secureImportAllData(file: File): Promise<DataImportResult> {
    try {
      // 1. Vérification de sécurité
      await this.performSecurityCheck('IMPORT_ALL_DATA')
      
      // 2. Créer backup automatique
      const backup = await this.createAutomaticBackup('Backup avant import complet')
      
      // 3. Log de l'action
      await this.logAuditAction('IMPORT_ALL_DATA_INITIATED', {
        backupId: backup.id,
        fileName: file.name,
        fileSize: file.size
      })
      
      // 4. Effectuer l'import
      const result = await this.importAllData(file)
      
      // 5. Log de succès
      await this.logAuditAction('IMPORT_ALL_DATA_COMPLETED', {
        backupId: backup.id,
        result,
        success: result.success
      })
      
      return result
      
    } catch (error) {
      // Log de l'erreur
      await this.logAuditAction('IMPORT_ALL_DATA_FAILED', {
        error: (error as Error).toString(),
        success: false
      })
      throw error
    }
  }
}
